# Generated by Django 5.0 on 2024-09-21 23:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_categoria_cat",
                    ),
                ),
                (
                    "txtCategoria",
                    models.CharField(max_length=50, verbose_name="txt_categoria_cat"),
                ),
                (
                    "dataInicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="dat_inicio_cat"
                    ),
                ),
                (
                    "dataFim",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="dat_fim_cat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusEvento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_status_evento_sev",
                    ),
                ),
                (
                    "txtStatusEvento",
                    models.CharField(
                        max_length=50, verbose_name="txt_status_evento_sev"
                    ),
                ),
                (
                    "dataInicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="dat_inicio_eve"
                    ),
                ),
                (
                    "dataFim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dat_fim_eve"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numOcorrencia",
                    models.CharField(max_length=11, verbose_name="num_ocorrencia"),
                ),
                (
                    "txtProblema",
                    models.CharField(max_length=1000, verbose_name="txtProblema"),
                ),
                (
                    "txtEndereco",
                    models.CharField(max_length=500, verbose_name="txt_endereco_eve"),
                ),
                (
                    "txtLat",
                    models.CharField(max_length=20, verbose_name="txt_latitude_eve"),
                ),
                (
                    "txtLong",
                    models.CharField(max_length=20, verbose_name="txt_longitude_eve"),
                ),
                ("file", models.BinaryField(verbose_name="img_file_eve")),
                (
                    "dataInicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="dat_inicio_eve"
                    ),
                ),
                (
                    "dataFim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dat_fim_eve"
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoHistorico",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_evento_historico_ehi",
                    ),
                ),
                ("dataInicio", models.DateTimeField(verbose_name="dat_inicio_ehi")),
                (
                    "dataFim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dat_fim_ehi"
                    ),
                ),
                (
                    "idEvento",
                    models.ForeignKey(
                        db_column="id_evento_ehi",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="pages.evento",
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        db_column="id_usuario_ehi",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoObservacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_evento_observacao_eob",
                    ),
                ),
                (
                    "txtObservacao",
                    models.CharField(
                        max_length=500, verbose_name="txt_evento_observacao_eob"
                    ),
                ),
                ("dataInicio", models.DateTimeField(verbose_name="dat_inicio_eob")),
                (
                    "dataFim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dat_fim_eob"
                    ),
                ),
                (
                    "idEventoHistorico",
                    models.ForeignKey(
                        db_column="id_evento_historico_eob",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="pages.eventohistorico",
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        db_column="id_usuario_eob",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoesUsuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventohistorico",
            name="listObservacao",
            field=models.ManyToManyField(
                related_name="observacoesHistorico", to="pages.eventoobservacao"
            ),
        ),
        migrations.AddField(
            model_name="eventohistorico",
            name="idStatusEvento",
            field=models.ForeignKey(
                db_column="id_status_evento_ehi",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historicos",
                to="pages.statusevento",
            ),
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_subcategoria_sub",
                    ),
                ),
                (
                    "txtSubcategoria",
                    models.CharField(
                        max_length=100, verbose_name="txt_subcategoria_sub"
                    ),
                ),
                (
                    "dataInicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="dat_inicio_eve"
                    ),
                ),
                (
                    "txtDescricao",
                    models.CharField(max_length=500, verbose_name="txt_descricao_sub"),
                ),
                (
                    "dataFim",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="dat_fim_eve",
                    ),
                ),
                (
                    "idCategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.categoria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="idSubcategoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.subcategoria"
            ),
        ),
    ]
