# Generated by Django 5.0 on 2024-09-22 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="dataFim",
            field=models.DateTimeField(blank=True, null=True, verbose_name="data_fim"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="dataInicio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="data_inicio"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id_categoria"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="txtCategoria",
            field=models.CharField(max_length=50, verbose_name="categoria"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="dataFim",
            field=models.DateTimeField(blank=True, null=True, verbose_name="dat_fim"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="dataInicio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="dat_inicio"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                verbose_name="Insira uma foto:",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="txtEndereco",
            field=models.CharField(max_length=500, verbose_name="Endereco"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="txtLat",
            field=models.CharField(max_length=20, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="txtLong",
            field=models.CharField(max_length=20, verbose_name="longitude"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="txtProblema",
            field=models.CharField(max_length=1000, verbose_name="Problema"),
        ),
        migrations.AlterField(
            model_name="statusevento",
            name="dataFim",
            field=models.DateTimeField(blank=True, null=True, verbose_name="data_fim"),
        ),
        migrations.AlterField(
            model_name="statusevento",
            name="dataInicio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="data_inicio"
            ),
        ),
        migrations.AlterField(
            model_name="statusevento",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id_status_evento"
            ),
        ),
        migrations.AlterField(
            model_name="statusevento",
            name="txtStatusEvento",
            field=models.CharField(max_length=50, verbose_name="status_evento"),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="dataFim",
            field=models.DateTimeField(blank=True, null=True, verbose_name="data_fim"),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="dataInicio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="dat_inicio"
            ),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id_subcategoria"
            ),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="txtDescricao",
            field=models.CharField(max_length=500, verbose_name="txt_descricao"),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="txtSubcategoria",
            field=models.CharField(max_length=100, verbose_name="subcategoria"),
        ),
    ]
